const places = [
  { name: "Margit-island",
    type: ["park"],
    lat: 47.525358,
    lng: 19.046662,
    description: "Nice park in the middle of the Danube, great for walking and cycling. There are also some historical buildings and a small zoo, as well as a musical fountain.",
    link: "https://margitsziget.hu"
  },
  { name: "Városliget",
    type: ["park"],
    lat: 47.5141,
    lng: 19.0830,
    description: "A large public park in Budapest, home to the City Park, museums, and the famous Széchenyi Thermal Bath.",
    link: "https://en.wikipedia.org/wiki/Városliget"
  },
  { name: "Gellért Hill",
    type: ["park"],
    lat: 47.486390,
    lng: 19.048904,
    description: "A prominent hill in Budapest offering panoramic views of the city, with historical significance and the Citadella fortress.",
    link: "https://en.wikipedia.org/wiki/Gellért_Hill"
  },
  { name: "Kopaszi-dam",
    type: ["park"],
    lat: 47.466343,
    lng: 19.063308,
    description: "A scenic area along the Danube River, ideal for walking, cycling, and enjoying nature, with restaurants and cafes.",
    link: "https://www.budapart.hu/en"
  },
  { name: "Normafa",
    type: ["park"],
    lat: 47.503088, 
    lng: 18.965749,
    description: "A popular recreational area in the Buda Hills, known for its hiking trails, panoramic views, and outdoor activities.",
    link: "https://normafapark.hu/"
  },
  { name: "Millenáris Park",
    type: ["park"],
    lat: 47.510277, 
    lng: 19.027462,
    description: "A cultural and recreational park in Budapest, featuring exhibitions, events, and green spaces, located in the former Ganz Works factory area.",
    link: "https://hu.wikipedia.org/wiki/Millen%C3%A1ris_Park"
  },
  { name: "Heroes' Square",
    type: ["historical", "monument"],
    lat: 47.514793, 
    lng: 19.077753,
    description: "A major square in Budapest, known for its iconic statues of Hungarian leaders and the Millennium Monument",
    link: "https://en.wikipedia.org/wiki/Heroes%27_Square_(Budapest)"
  },
  { name: "Buda Castle",
    type: ["historical", "monument"],
    lat: 47.496089,
    lng: 19.039392,
    description: "A historical castle and palace complex of the Hungarian kings in Budapest, offering stunning views of the city and housing museums.",
    link: "https://en.wikipedia.org/wiki/Buda_Castle"
  },
  { name: "Fisherman's Bastion",
    type: ["historical", "monument"],
    lat: 47.502598,
    lng: 19.034543,
    description: "A neo-Romanesque terrace in Budapest, known for its panoramic views of the Danube and the city, and its distinctive turrets.",
    link: "https://en.wikipedia.org/wiki/Fisherman%27s_Bastion"
  },
  {name : "Andrassy Avenue",
    type: ["historical", "monument"],
    lat: 47.506548,
    lng: 19.065356,
    description: "A historic boulevard in Budapest, known for its grand architecture, cultural institutions, and as a UNESCO World Heritage site.",
    link: "https://hu.wikipedia.org/wiki/Andr%C3%A1ssy_%C3%BAt"
  },
  {name : "Parlament",
    type: ["historical", "monument"],
    lat: 47.506881,
    lng: 19.045808,
    description: "The seat of the National Assembly of Hungary, an iconic building on the banks of the Danube, known for its stunning architecture.",
    link: "https://en.wikipedia.org/wiki/Hungarian_Parliament_Building"
  },
  {name : "Chain Bridge",
    type: ["historical", "monument"],
    lat: 47.498909,
    lng: 19.043641,
    description: "A historic suspension bridge that spans the Danube River, connecting Buda and Pest, and a symbol of Budapest.",
    link: "https://en.wikipedia.org/wiki/Chain_Bridge_(Budapest)"
  },
  { name: "Liberty Bridge",
    type: ["historical", "monument"],
    lat: 47.485671,
    lng: 19.054971,
    description: "A beautiful green bridge over the Danube, known for its Art Nouveau design and historical significance.",
    link: "https://en.wikipedia.org/wiki/Liberty_Bridge_(Budapest)" 
  },
  {name: "Great Market Hall",
    type: ["historical", "monument", "market"],
    lat: 47.486781,
    lng: 19.058876,
    description: "The largest and oldest indoor market in Budapest, offering a wide variety of local produce, meats, spices, and souvenirs.",
    link: "https://en.wikipedia.org/wiki/Great_Market_Hall"
  },
  {name: "Bartók Béla Boulevard",
    type: ["historical", "monument"],
    lat: 47.480408,
    lng: 19.051902,
    description: "A vibrant street in the Buda district known for its cultural significance, lined with cafes, galleries, and shops.",
    link: "https://hu.wikipedia.org/wiki/Bart%C3%B3k_B%C3%A9la_%C3%BAt"
  },
  {name: "Vajdahunyad Castle",
    type: ["historical", "monument"],
    lat: 47.515252,
    lng: 19.082190,
    description: "A picturesque castle in City Park, showcasing various architectural styles and housing the Hungarian Museum of Agriculture.",
    link: "https://en.wikipedia.org/wiki/Vajdahunyad_Castle"
  },
  {name: "Ethnographic Museum",
    type: ["historical", "museum"],
    lat: 47.511795,
    lng: 19.081203,
    description: "On the roof of the museum, you can find a beautiful terrace with a view of the City Park and the Vajdahunyad Castle. The museum itself showcases Hungarian ethnography and folk culture.",
    link: "https://en.wikipedia.org/wiki/Ethnographic_Museum_(Budapest)"
  },
  { name: "Aquincum Amfitheatre",
    type: ["historical", "monument"],
    lat: 47.532915,
    lng: 19.038974,
    description: "A well-preserved Roman amphitheater in the Aquincum archaeological site, offering insights into ancient Roman entertainment and architecture.",
    link: "https://en.wikipedia.org/wiki/Aquincum" 
  },
  { name: "Krumplis lángos",
    type: ["food"],
    lat: 47.541252,
    lng: 19.041066,
    description: "The best lángos in Budapest, a popular Hungarian street food made of deep-fried flatbread topped with garlic, sour cream, and cheese.",
    link: "https://en.wikipedia.org/wiki/L%C3%A1ngos"
  },
  { name: "Oktogon Kürtőskalács",
    type: ["food"],
    lat: 47.505610,
    lng: 19.063217,
    description: "Best price for kürtőskalács in Budapest, a traditional Hungarian pastry also known as chimney cake, made of sweet dough rolled in sugar and baked on a spit.",
    link: "https://en.wikipedia.org/wiki/K%C3%BCrt%C5%91skal%C3%A1cs"
  },
  { name: "Budafok street butcher",
    type: ["food"],
    lat: 47.476495,
    lng: 19.053471,
    description: "A local butcher shop, which also offers meals, like black pudding, sasuages, deep fried things, etc. If you are looking for an authentic Hungarian experience, this is the place to go.",
    link: "https://www.facebook.com/budafok.hentes"
  },
  {name: "Nokedlish",
    type: ["food"],
    lat: 47.495483,
    lng: 19.065718, 
    description: "A small street food place in the city center, known for its delicious Hungarian-style dumplings (nokedli) served with various toppings.",
    link: "https://www.facebook.com/nokedlish.streetfood"
  },
  {name: "VakVarjú Restaurant",
    type: ["food"], 
    lat: 47.499538,
    lng: 19.056156,
    description: "A popular restaurant (chain) in the city center, known for its traditional Hungarian dishes and cozy atmosphere.",
    link: "https://vakvarju.com/en/fooldal-english/"
  },




];
